/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/components/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/app/**/*.{js,ts,jsx,tsx,mdx}",
	],
	safelist: [
		"fill-crema",
		"fill-midnight",
		"fill-silver",
		"fill-gold",
		"border-midnight",
		"border-silver",
		"border-gold",
		"bg-bronze",
		"bg-silver",
		"bg-gold",
		"border-1cost",
		"border-2cost",
		"border-3cost",
		"border-4cost",
		"border-5cost",
		"bg-1cost",
		"bg-2cost",
		"bg-3cost",
		"bg-4cost",
		"bg-5cost",
		"text-1cost",
		"text-2cost",
		"text-3cost",
		"text-4cost",
		"text-5cost",
		"bg-3cost",
		"w-2.5",
		"w-3",
		"w-4",
	],
	theme: {
		screens: {
			sm: "600px",
			md: "820px",
			lg: "1110px",
			xl: "1280px",
		},
		container: {
			center: true,
		},
		colors: {
			midnight: "#041C32",
			earlynight: "#04293A",
			midday: "#064663",
			morning: "#ECB365",
			crema: "#ffffd2",
			bronze: "#9f561b",
			silver: "#b5cbde",
			gold: "#f9be0a",
			"1cost": "#9f9a89",
			"2cost": "#39b65a",
			"3cost": "#2875be",
			"4cost": "#aa09a4",
			"5cost": "#d78e00",
			support: "#39b65a",
			carry: "#8b52e9",
		},
	},
	plugins: [],
};
