export const augmentsDistributionDetailed = [
  {
    1: "Silver",
    2: "Silver",
    3: "Gold",
    percent: 5
  }, {
    1: "Silver",
    2: "Silver",
    3: "Prismatic",
    percent: 5
  }, {
    1: "Silver",
    2: "Gold",
    3: "Gold",
    percent: 12
  }, {
    1: "Silver",
    2: "Gold",
    3: "Prismatic",
    percent: 5
  }, {
    1: "Silver",
    2: "Prismatic",
    3: "Prismatic",
    percent: 1
  }, {
    1: "Gold",
    2: "Silver",
    3: "Gold",
    percent: 18
  }, {
    1: "Gold",
    2: "Silver",
    3: "Prismatic",
    percent: 2
  }, {
    1: "Gold",
    2: "Gold",
    3: "Gold",
    percent: 22
  }, {
    1: "Gold",
    2: "Gold",
    3: "Prismatic",
    percent: 3
  }, {
    1: "Gold",
    2: "Prismatic",
    3: "Silver",
    percent: 6
  }, {
    1: "Gold",
    2: "Prismatic",
    3: "Gold",
    percent: 10
  }, {
    1: "Gold",
    2: "Prismatic",
    3: "Prismatic",
    percent: 1
  }, {
    1: "Prismatic",
    2: "Silver",
    3: "Gold",
    percent: 4
  }, {
    1: "Prismatic",
    2: "Silver",
    3: "Prismatic",
    percent: 1
  }, {
    1: "Prismatic",
    2: "Gold",
    3: "Gold",
    percent: 2
  }, {
    1: "Prismatic",
    2: "Gold",
    3: "Prismatic",
    percent: 1
  }, {
    1: "Prismatic",
    2: "Prismatic",
    3: "Gold",
    percent: 1
  }, {
    1: "Prismatic",
    2: "Prismatic",
    3: "Prismatic",
    percent: 1
  }
]
export const augmentsDistribution = [
  {
    "tier": "Silver",
    1: 28,
    2: 35,
    3: 6
  }, {
    "tier": "Gold",
    1: 62,
    2: 45,
    3: 74
  }, {
    "tier": "Prismatic",
    1: 10,
    2: 20,
    3: 20
  },
]